name: cupertino_refresh
description: iOS-styled pull to refresh control Widget and Sliver for Flutter.
version: 0.9.1
homepage: https://github.com/porelarte/cupertino-refresh

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: