name: cupertino_refresh
description: iOS style pull to refresh indicator for Flutter.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: