name: cupertino_refresh
description: Package of iOS-styled refresh control Widget and Sliver for Flutter.
version: 0.9.5
homepage: https://github.com/porelarte/cupertino-refresh

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: